language: php

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
  email: false
  slack:
    secure: dIDzk0wWDoXA815uIDgQbKHyi7hRPG6ufZ6cjIJJiPuFHifsC1tqEAFkbtpT8R7i5snYBDo3GX+3q/2+vwtVfPEkYiS9Jmew/yHdGoQHqjpV4wCMTtGx1ViC8bAUldTx+QnmWVnRlYKYMakbZQSgTVhjlfBEVjXhmOw0uEqAw3s=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
